export const ASCENSION_CLASSES = [
  'Barbarian',
  'Bloodmage',
  'Chronomancer',
  'Cultist',
  'Felsworn',
  'Guardian',
  'Knight of Xoroth',
  'Necromancer',
  'Primalist',
  'Pyromancer',
  'Ranger',
  'Reaper',
  'Runemaster',
  'Starcaller',
  'Stormbringer',
  'Sun Cleric',
  'Templar',
  'Tinker',
  'Venomancer',
  'Witch Doctor',
  'Witch Hunter'
];

export const CLASS_COLORS = {
  'Barbarian':       '#C41E3A',
  'Bloodmage':       '#E35252',
  'Chronomancer':   '#69CCF0',
  'Cultist':        '#A335EE',
  'Felsworn':       '#A35C25',
  'Guardian':       '#F58CBA',
  'Knight of Xoroth':'#C41F3B',
  'Necromancer':    '#4D5D53',
  'Primalist':      '#FF7C0A',
  'Pyromancer':     '#FF4500',
  'Ranger':         '#AAD372',
  'Reaper':         '#71D5C4',
  'Runemaster':     '#00FF96',
  'Starcaller':     '#FFF569',
  'Stormbringer':   '#0070DD',
  'Sun Cleric':     '#F4C430',
  'Templar':        '#F58CBA',
  'Tinker':         '#E6CC80',
  'Venomancer':     '#ABD473',
  'Witch Doctor':   '#00FF96',
  'Witch Hunter':   '#D4AF37'
};